---
# https://kafka.apache.org/quickstart-docker
# https://linuxhint.com/docker_compose_kafka/

version: '2'
  services:
    kafkabroker:
      image: apache-kafka/broker:2.5.0
      hostname: kafka-broker
      container_name: kafka-broker
      ports:
      - "9092:9092"
  idaas-eventbuilder:
    image: maven
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - "./:/app:Z,delegated"
      # Mounting user's local .m2-directory,
      # for custom settings.xml and for caching dependencies.
      - "~/.m2:/root/.m2:Z,delegated"
    ports:
      - 2081:2081 # ZooKepper port
      - 9092:9092 # Kafka port
      - 8080:8080 # Backend HTTP server port
    working_dir: /app
    command: "mvn clean install"
    links:
      - kafkabroker
